version: '3.7'
# create networks with: 
# docker network create web
# docker network create --internal caddy_internal 
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/docker-pi/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/caddy-data:/data
      - /home/ubuntu/caddy-config:/config
      - /home/ubuntu/hugo-site/public/:/var/www/html
    networks:
      - web
      - internal
    restart: unless-stopped

  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    restart: unless-stopped
    ports:
      - "127.0.0.1:5232:5232"
    volumes:
      - /home/ubuntu/radicale-data/:/data/:rw
      - /home/ubuntu/docker-pi/radicale-config:/config/:ro
    networks:
      - internal
