version: '3.7'
# create networks with: 
# docker network create web
# docker network create --internal caddy_internal 
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/docker-pi/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/caddy-data:/data
      - /home/ubuntu/caddy-config:/config
      - /var/www/html:/var/www/html
    networks:
      - web
      - internal


