version: '3.7'

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/docker-pi/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/caddy-data:/data
      - /home/ubuntu/caddy-config:/config
    networks:
      - web
      - internal


