version: '3.7'
# create networks with: 
# docker network create web
# docker network create --internal caddy_internal 
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /home/ml/docker-pi/Caddyfile:/etc/caddy/Caddyfile
      - /home/ml/caddy-data:/data
      - /home/ml/caddy-config:/config
      - /home/ml/hugo-site/public/:/var/www/html
    networks:
      - web
      - internal
    restart: unless-stopped

  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    restart: unless-stopped
    ports:
      - "127.0.0.1:5232:5232"
    volumes:
      - /home/ml/radicale-data/:/data/:rw
      - /home/ml/docker-pi/radicale-config:/config/:ro
    networks:
      - internal

  # syncthing:
  #   image: syncthing/syncthing
  #   container_name: syncthing
  #   hostname: my-syncthing
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - /wherever/st-sync:/var/syncthing
  #   ports:
  #     - 8384:8384 # Web UI
  #     - 22000:22000/tcp # TCP file transfers
  #     - 22000:22000/udp # QUIC file transfers
  #     - 21027:21027/udp # Receive local discovery broadcasts
  #   restart: unless-stopped
  #   networks:
  #     - web
