---
# https://sitegeist.de/blog/typo3-blog/docker-compose-setup-mit-nginx-reverse-proxy.html
# https://docs.docker.com/compose/networking/
version: '2'
services:
  frontproxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
        #networks:
        #- nginx

        #networks:
        #  nginx:
        #    driver: bridge
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.localhost
