---
# https://sitegeist.de/blog/typo3-blog/docker-compose-setup-mit-nginx-reverse-proxy.html
# https://docs.docker.com/compose/networking/
version: '2'
services:
  frontproxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx
    restart: always
    environment:
      - DEFAULT_HOST=selfhostgang.dynv6.net
      - ENABLE_IPV6=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    networks:
        - nginx
  nginx-letsencrypt-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "./certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "frontproxy"
volumes:
  certs-volume:

networks:
  nginx:
    driver: bridge
